services:
  pg-dev:
    image: postgres:16
    environment:
      POSTGRES_USER: SBE_PROD
      POSTGRES_PASSWORD: SBE_PWS
      POSTGRES_DB: transportistas_dev
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata-dev:/var/lib/postgresql/data

# docker-compose up -d
# docker compose stop
# docker compose down (Borra contenedor y volumenes)